[colors]
draw_bold_text_with_bright_colors = true

# Colors (Ayu Dark)

# Catppuccino theme scheme for Alacritty

[colors.primary]
background = '#1E1E2E'
foreground = '#D6D6D6'

[colors.cursor]
text = '#1E1E2E'
cursor = '#D9D9D9'

[colors.normal]
black = '#181A1F'
red = '#E86671'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#54AFBC'
white = '#ABB2BF'

[colors.bright]
black = '#5C6370'
red = '#E86671'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#54AFBC'
white = '#F7F7F7'

[colors.dim]
black = '#5C6370'
red = '#74423F'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#6E4962'
cyan = '#5C8482'
white = '#828282'

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
# style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
# style = "BoldItalic"

[font.italic]
family = "JetBrainsMono Nerd Font"
# style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
# style = "Regular"

[window]
decorations = "Transparent"
opacity = 1
blur = true
option_as_alt = "OnlyLeft"
dynamic_padding = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 15

[keyboard]
bindings = [
{ key= "Left", mods= "Alt", chars= "\u001BB" } # Skip word left
,{ key= "Right", mods= "Alt", chars= "\u001BF" } # Skip word right
,{ key= "Left", mods= "Command", chars= "\u001bOH", mode= "AppCursor" } # Home
,{ key= "Right", mods= "Command", chars= "\u001bOF", mode= "AppCursor" } # End
,{ key= "Back", mods= "Command", chars= "\u0015" } # Delete line
,{ key= "Back", mods= "Alt", chars= "\u001b\u007f" } # Delete word
,{ key= "c", mods= "Command", action= "Copy" } # Copy to Clipboard
]

[cursor.style]
blinking = "On"

[cursor]
blink_interval = 500
blink_timeout = 0
