[colors]
draw_bold_text_with_bright_colors = true

# Colors (Ayu Dark)

# Default colors
[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'


[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "Transparent"
opacity = 0.9
blur = true
option_as_alt = "OnlyLeft"
dynamic_padding = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 15

[keyboard]
bindings = [
{ key= "Left", mods= "Alt", chars= "\u001BB" } # Skip word left
,{ key= "Right", mods= "Alt", chars= "\u001BF" } # Skip word right
,{ key= "Left", mods= "Command", chars= "\u001bOH", mode= "AppCursor" } # Home
,{ key= "Right", mods= "Command", chars= "\u001bOF", mode= "AppCursor" } # End
,{ key= "Back", mods= "Command", chars= "\u0015" } # Delete line
,{ key= "Back", mods= "Alt", chars= "\u001b\u007f" } # Delete word
,{ key= "c", mods= "Command", action= "Copy" } # Copy to Clipboard
]

[cursor.style]
blinking = "On"

[cursor]
blink_interval = 500
blink_timeout = 0
